version: '3.6'

services:

  mqtt_broker:
    build: ./mqtt_broker
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
  
  box_service:
    build: ./box_service
    restart: unless-stopped
    container_name: box-service
    ports:
      - 80:80
    depends_on:
      - mqtt_broker
